name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - run: echo "Installing chembl_structure pipeline"
        - run: conda install -c conda-forge chembl_structure_pipeline
        - uses: fastai/workflows/nbdev-ci@master
        
