# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/chemtools',
                'doc_host': 'https://marcossantanaioc.github.io',
                'git_url': 'https://github.com/marcossantanaioc/chemtools',
                'lib_path': 'chemtools'},
  'syms': {'chemtools.core': {'chemtools.core.foo': ('core.html#foo', 'chemtools/core.py')}}}