name: pipeline
on:
  push:
    branches:
      - 'main'
      - 'dev'

permissions:
  contents: read

jobs:
  build: # Name of first job.
    runs-on: ubuntu-latest # Defines the runner that will run the job.
    timeout-minutes: 5
    steps: # Steps in the job
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: actions/checkout@v3
      - name: Install
        run: |
          echo "Installing chemtools"
          python -m pip install --upgrade pip
          python setup.py install
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: chemtools_artifact
          path: .
  verify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: flake8
        run: |
            python -m pip install flake8
            flake8 . --show-source --statistics -v
      - name: pytest
        run: |
          cd cheminftools/test/tools && pytest -v