name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge
          auto-update-conda: true
        run: conda install -c conda-forge chembl_structure_pipeline
      - uses: fastai/workflows/nbdev-ci@master

