  GNU nano 2.9.3                                                                     .github/workflows/test.yaml                                                                                

name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/nbdev-ci@master
