name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - run: conda install -c conda-forge chembl_structure_pipeline
        - uses: actions/checkout@v2/fastai/workflows/nbdev-ci@master
        - run: conda install -c conda-forge chembl_structure_pipeline
        
