name: pipeline # Name of the workflow
on: [push, release, workflow_dispatch] # Trigger - Make sure we can activate workflow manually.

permissions:
  contents: read

jobs:
  build: # Name of first job.
    runs-on: ubuntu-latest # Defines the runner that will run the job.
    steps: # Steps in the job
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: install
        run: |
          echo "Installing chemtools"
          python -m pip install --upgrade pip
          python setup.py install
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: chemtools_artifact
          path: .
  verify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: flake8
        run: |
            python -m pip install flake8
            flake8 . --show-source --statistics

  deploy:
    needs: verify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: marcossantana
        password: ${{ secrets.pip_token }}
