name: pipeline # Name of the workflow
on: push # Make sure we can activate workflow manually.
jobs:
  build: # Name of first job.
    runs-on: ubuntu-latest # Defines the runner that will run the job.
    steps: # Steps in the job
      - name: print greeting
        run: |
          echo "Hello world"
          echo "Testing multiline"

      - name: finish up
        run: |
          echo "Finishing the job"


